services:
  huridocs:
    image: byunbyun/huridocs-sm120:updated
    container_name: huridocs-api
    ports:
      - "8001:5060"
    environment:
      - PYTHONUNBUFFERED=1
      - TOKENIZERS_PARALLELISM=false
      # PyTorch 경고 로그 억제
      - PYTHONWARNINGS=ignore::UserWarning
      - TRANSFORMERS_VERBOSITY=error
      # 오프라인 모드 활성화 - 인터넷 다운로드 비활성화
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - pdf-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - pdf-network
    restart: unless-stopped

networks:
  pdf-network:
    driver: bridge